### ISSUE TITLE
pkg doesn't appear in list of packages available

### ISSUE THREAD

**Issue by juliadupin** [rbouckaert/FixedTreeAnalysis#2]
Dear Remco,

thanks for putting together this package!
FixedTreeAnalysis does not yet show in the list of packages available for installation. Do you have an estimate for when it will be available?
When I installed it by hand, even though the template option shows up in the drop down menu, selecting it doesn't work.

Thanks!

Julia

**Comment by rbouckaert** [comment]
Hi Julia, 

Thanks for your interest -- the package is not yet properly tested, so is not in the main package repository. However, it is in the package-extras-2.7 repository, which you can add in BEAUti through menu `File => Manage Packages => Package Repositories => Add URL` then add `https://raw.githubusercontent.com/CompEvol/CBAN/master/packages-extra-2.7.xml` in the entry and click `OK`. Then click `Close` and the package should appear in the list (together with a few other experimental packages).

You mentioned that it does not work -- selecting the `File => Templates => Fixed Tree Analysis` followed by `File => Import fixed tree` (and select a tree file) should give you an entry in the partitions panel. Do you get this far, or does it fail later?

Cheers,

Remco

**Comment by juliadupin** [comment]
Hi Remco,

installing it through the package extras repository worked out fine. I was able to follow the tutorial without any issues.
Thanks for the help!

Julia

**Comment by rbouckaert** [comment]
Glad to see it worked :)
